sonar.projectKey=devops-taskmaster-core
sonar.projectName=TaskMaster-Enterprise-Core
sonar.projectVersion=1.1

# Quality Gate: Fail if coverage is below 80% on NEW code
sonar.qualitygate.wait=true

# Analysis parameters
sonar.sources=app/src/main/java
sonar.java.binaries=app/target/classes
sonar.leak.period=previous_version

